---
- name: Execute command on AWS instance
  hosts: webservers
  become: true
  tasks:
    - name: Run command
      shell: uptime
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout_lines
