- name: Install web servers
  hosts: webservers
  become: true

  tasks:
    - name: Install IIS on Windows servers
      win_feature:
        name: Web-Server
        state: present
      when: ansible_os_family == "Windows"

    - name: Install Apache on Linux servers
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"
      
    - name: Install Apache on Debian servers
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
