---
- name: Ping All Servers
  hosts: webservers
  gather_facts: yes
  vars_files:
    - vault/credentials.yml
  tasks:
    - name: Ping Linux hosts
      ping:
      when: "'linux' in group_names"

    - name: Ping Windows hosts
      win_ping:
      when: "'windows' in group_names"
